In [2]:
import pandas as pd

In [3]:
data = pd.read_csv("D:\\Academics\\Kavach\\Implementation\\Level 3\\website_urls.csv")

In [4]:
X = data.drop(['Result','index'],axis=1)
Y = data["Result"]

In [5]:
X

having_IPhaving_IP_Address  URLURL_Length  Shortining_Service  \
0                              -1              1                   1   
1                               1              1                   1   
2                               1              0                   1   
3                               1              0                   1   
4                               1              0                  -1   
...                           ...            ...                 ...   
11050                           1             -1                   1   
11051                          -1              1                   1   
11052                           1             -1                   1   
11053                          -1             -1                   1   
11054                          -1             -1                   1   

       having_At_Symbol  double_slash_redirecting  Prefix_Suffix  \
0                     1                        -1             -1   
1                     1                         1             -1   
2                     1                         1             -1   
3                     1                         1             -1   
4                     1                         1             -1   
...                 ...                       ...            ...   
11050                -1                         1              1   
11051                -1                        -1             -1   
11052                 1                         1             -1   
11053                 1                         1             -1   
11054                 1                         1             -1   

       having_Sub_Domain  SSLfinal_State  Domain_registeration_length  \
0                     -1              -1                           -1   
1                      0               1                           -1   
2                     -1              -1                           -1   
3                     -1              -1                            1   
4                      1               1                           -1   
...                  ...             ...                          ...   
11050                  1               1                           -1   
11051                  1              -1                           -1   
11052                  1              -1                           -1   
11053                 -1              -1                            1   
11054                 -1              -1                            1   

       Favicon  ...  RightClick  popUpWidnow  Iframe  age_of_domain  \
0            1  ...           1            1       1             -1   
1            1  ...           1            1       1             -1   
2            1  ...           1            1       1              1   
3            1  ...           1            1       1             -1   
4            1  ...           1           -1       1             -1   
...        ...  ...         ...          ...     ...            ...   
11050       -1  ...          -1           -1      -1              1   
11051       -1  ...           1           -1       1              1   
11052        1  ...           1            1       1              1   
11053       -1  ...           1           -1       1              1   
11054        1  ...           1            1       1             -1   

       DNSRecord  web_traffic  Page_Rank  Google_Index  \
0             -1           -1         -1             1   
1             -1            0         -1             1   
2             -1            1         -1             1   
3             -1            1         -1             1   
4             -1            0         -1             1   
...          ...          ...        ...           ...   
11050          1           -1         -1             1   
11051          1            1          1             1   
11052          1            1         -1             1   
11053          

In [6]:
from sklearn.model_selection import train_test_split 
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.3, random_state = 0) 

In [7]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators = 30 )
clf.fit(X_train, Y_train)
Y_pred =clf.predict(X_test)

In [8]:
import pickle
pickle.dump(clf,open('level3.pkl','wb'))

# clf.save("level3.pkl")

In [9]:
from features import FeatureExtraction
import numpy as np
checkprediction = FeatureExtraction("www.atlas-games.com/onceuponatime/")
x = np.array(checkprediction.getFeaturesList()).reshape(1,30)

In [10]:
x

array([[ 1,  1,  1,  1,  1,  1,  0, -1, -1, -1,  1,  1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1, -1,  1]])

In [13]:
 loaded_model = pickle.load(open('level3.pkl', 'rb'))
loaded_model.predict(x)

array([-1], dtype=int64)

In [16]:
pred =pd.DataFrame(Y_pred)

In [17]:
from sklearn import metrics
print(metrics.confusion_matrix(Y_test, Y_pred))
print(metrics.classification_report(Y_test, Y_pred))
print('\nAccuracy Score:')
print(metrics.accuracy_score(Y_test,Y_pred))

[[ 543  955]
 [ 606 1213]]
              precision    recall  f1-score   support

          -1       0.47      0.36      0.41      1498
           1       0.56      0.67      0.61      1819

    accuracy                           0.53      3317
   macro avg       0.52      0.51      0.51      3317
weighted avg       0.52      0.53      0.52      3317


Accuracy Score:
0.5293940307506784


## Ensemble learning

In [ ]:
# Import necessary libraries
from sklearn.ensemble import VotingClassifier, GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [12]:

# Split data into training and testing sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3)

# Create classifiers
knn = KNeighborsClassifier(n_neighbors=3)
dt = DecisionTreeClassifier(max_depth=5)
gb = GradientBoostingClassifier(n_estimators=100, learning_rate=1.0, max_depth=1, random_state=0)

# Create ensemble of classifiers using multistack type
ensemble = VotingClassifier(estimators=[('knn', knn), ('dt', dt), ('gb', gb)], voting='soft', flatten_transform=True)

In [14]:
ensemble.fit(X_train, Y_train)

VotingClassifier(estimators=[('knn', KNeighborsClassifier(n_neighbors=3)),
                             ('dt', DecisionTreeClassifier(max_depth=5)),
                             ('gb',
                              GradientBoostingClassifier(learning_rate=1.0,
                                                         max_depth=1,
                                                         random_state=0))],
                 voting='soft')

In [15]:
Y_pred =ensemble.predict(X_test)

In [18]:
from sklearn import metrics
print(metrics.confusion_matrix(Y_test, Y_pred))
print(metrics.classification_report(Y_test, Y_pred))
print('\nAccuracy Score:')
print(metrics.accuracy_score(Y_test,Y_pred))

[[ 543  955]
 [ 606 1213]]
              precision    recall  f1-score   support

          -1       0.47      0.36      0.41      1498
           1       0.56      0.67      0.61      1819

    accuracy                           0.53      3317
   macro avg       0.52      0.51      0.51      3317
weighted avg       0.52      0.53      0.52      3317


Accuracy Score:
0.5293940307506784
